import { Resend } from 'resend';
import { config } from '../config.js';

const resend = new Resend(config.resendApiKey);

export interface SendDraftEmailParams {
  to: string;
  subject: string;
  content: string;
  userName: string;
  userEmail: string;
  draftType: string;
}

export interface EmailResult {
  success: boolean;
  messageId?: string;
  error?: string;
}

export async function sendDraftEmail(params: SendDraftEmailParams): Promise<EmailResult> {
  const { to, subject, content, userName, userEmail, draftType } = params;

  if (!config.resendApiKey) {
    console.error('[Email] Resend API key not configured');
    return { success: false, error: 'Email service not configured' };
  }

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { border-bottom: 2px solid #0a0a0a; padding-bottom: 16px; margin-bottom: 24px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: 500; margin-bottom: 16px; }
    .badge-removal { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }
    .badge-legal { background: #ecfdf5; color: #059669; border: 1px solid #a7f3d0; }
    .badge-privacy { background: #f0f9ff; color: #0284c7; border: 1px solid #bae6fd; }
    .content { white-space: pre-wrap; margin-bottom: 32px; }
    .footer { border-top: 1px solid #e5e5e5; padding-top: 16px; font-size: 14px; color: #666; }
    .legal { font-size: 12px; color: #999; margin-top: 24px; font-style: italic; }
  </style>
</head>
<body>
  <div class="header">
    <span class="badge ${getBadgeClass(draftType)}">${draftType}</span>
  </div>

  <div class="content">${escapeHtml(content)}</div>

  <div class="footer">
    <p>---</p>
    <p>This request is made pursuant to applicable California consumer protection laws.</p>
    <p>Please confirm receipt and action within 45 days as required by law.</p>
    <p style="margin-top: 16px;">Sincerely,</p>
    <p><strong>${escapeHtml(userName)}</strong></p>
    <p>${escapeHtml(userEmail)}</p>
  </div>

  <div class="legal">
    <p>This document was generated by LitiGate and indicates potential eligibility only. Sent with user approval.</p>
  </div>
</body>
</html>
  `.trim();

  const textContent = `
${draftType}

${content}

---

This request is made pursuant to applicable California consumer protection laws.
Please confirm receipt and action within 45 days as required by law.

Sincerely,
${userName}
${userEmail}

---
This document was generated by LitiGate and indicates potential eligibility only. Sent with user approval.
  `.trim();

  try {
    console.log(`[Email] Sending ${draftType} to ${to}`);

    const { data, error } = await resend.emails.send({
      from: `LitiGate <${config.resendFromEmail}>`,
      to: [to],
      replyTo: userEmail,
      subject: subject,
      html: htmlContent,
      text: textContent,
    });

    if (error) {
      console.error('[Email] Resend error:', error);
      return { success: false, error: error.message };
    }

    console.log(`[Email] Sent successfully, ID: ${data?.id}`);
    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error('[Email] Send error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    };
  }
}

function getBadgeClass(type: string): string {
  switch (type) {
    case 'Data Broker Removal':
      return 'badge-removal';
    case 'Legal Claim':
      return 'badge-legal';
    case 'Privacy Request':
      return 'badge-privacy';
    default:
      return 'badge-removal';
  }
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
